import type { Metadata } from "next";
import styles from "./main.module.css";
import Image from "next/image";
import Link from "next/link";

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faRocket, faRoad, faUser, faGears, faRightFromBracket } from '@fortawesome/free-solid-svg-icons'
import { Ubuntu } from "next/font/google";

export const metadata: Metadata = {
  title: "dev-log",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${styles.background}`} >
        <nav className={styles.nav_bar}>
            <ul>
                <div className={styles.app_logo}>
                    <Image className={styles.logo_img} src="/ys.svg" width={30} height={30} alt="Logo" />
                    <h1>dev-log</h1>
                </div>
                <NavButton icon={faRocket} link={'/main'}>Journey</NavButton>
                <NavButton icon={faRoad} link={'/main/goal'}>Goals</NavButton>
                <NavButton icon={faUser} link={'/'}>Profile</NavButton>
                <NavButton icon={faGears} link={'/'}>Settings</NavButton>
                <LogOut icon={faRightFromBracket} link={'/'}>Log out</LogOut>
            </ul>
        </nav>
        {children}</body>
    </html>
  );
}

function NavButton({ children, icon, link }) {
    return (
        <li className={styles.nav_button}>
            <Link href={link}>
                <div className={styles.icon}>
                    <FontAwesomeIcon  icon={icon} />
                </div>
                <p>{children}</p>
            </Link>
        </li>
    );
}

function LogOut({ children, icon, link }) {
    return (
        <li className={`${styles.log_out} ${styles.nav_button}`}>
            <Link href={link}>
                <div className={styles.icon}>
                    <FontAwesomeIcon  icon={icon} />
                </div>
                <p>{children}</p>
            </Link>
        </li>
    );
}
